### RENDER https://yanezproject2library.onrender.com

### RENDER GET all authors in database
GET https://yanezproject2library.onrender.com/authors

### RENDER GET all titles in database 
GET https://yanezproject2library.onrender.com/titles

### GET all titles in database 
GET http://localhost:8080/titles

### GET all authors in database
GET http://localhost:8080/authors


###RENDER GET an author by ID (Mo Willems)
GET https://yanezproject2library.onrender.com/authors/646a85407eab2340292fe61f

### GET an author by ID (Amy Krouse Rosenthal)
GET https://yanezproject2library.onrender.com/authors/646a858b7eab2340292fe620

### RENDER GET a title by ID (Today I Will Fly!)
GET https://yanezproject2library.onrender.com/titles/64659093b272aefcca51607e

### GET a title by ID (I Wish You More)
GET https://yanezproject2library.onrender.com/titles/64685775bf42815a12a244e9


### POST add author to database 
POST https://yanezproject2library.onrender.com/authors HTTP/1.1 
Content-Type: application/json

{
  "authorLastName": "McTesterson",
  "authorFirstName": "Tester",
  "birthdate": "10/21/1989",
  "email": "testthis@hotmail.com"
}

### POST add title to database
POST https://yanezproject2library.onrender.com/titles HTTP/1.1 
Content-Type: application/json

{
  "title": "Sample",
  "genre": "Fiction",
  "audience": "Children",
  "publisher": "Chronicle Books LLC",
  "isbn": "9781452126999",
  "authorFirstName": "Testy",
  "authorLastName": "McTesterson"
}

### PUT: Update an author by ID (test)
PUT https://yanezproject2library.onrender.com/authors/646d5f0b57f98a16c4ab4b29 HTTP/1.1 
Content-Type: application/json

{
  "authorLastName": "McTesterson",
  "authorFirstName": "Testy",
  "birthdate": "10/03/2012",
  "email": "thisIsaTest@gmail.com"
}

### PUT: Update a title by ID (test)
PUT https://yanezproject2library.onrender.com/titles/646d5f0e57f98a16c4ab4b2a HTTP/1.1 
Content-Type: application/json

{
  "title": "Test",
  "genre": "Horror",
  "audience": "Adults",
  "publisher": "BYU-ID",
  "isbn": "0000000000000",
  "authorFirstName": "Testy",
  "authorLastName": "McTesterson"
}

### DELETE an author by ID (test)
DELETE https://yanezproject2library.onrender.com/authors/646d70b057ea8543eef69293 HTTP/1.1 
Content-Type: application/json

### DELETE a title by ID (test)
DELETE https://yanezproject2library.onrender.com/titles/646d60bb57f98a16c4ab4b2b HTTP/1.1 
Content-Type: application/json


###